<<<<<<< HEAD
server:
  servlet:
    context-path: /auth

=======
>>>>>>> fae96c615f08af72ac4b3c03d5870995cbbd51b0
spring:
  redis:
    database: 0
    host: 127.0.0.1
    password:
    timeout: 5000
    port: 6379