server:
  servlet:
    context-path: /auth
  port: 20000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth2?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    # password: 111111
    password: ENC(7Q5eImVqqN6adbA71jYuJQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password:
    timeout: 8000
    port: 6379
jasypt:
  encryptor:
    password: abc123