<<<<<<< HEAD
auth-server: http://localhost:8080/auth # 认证服务器地址
=======
auth-server: http://localhost:8080 # 认证服务器地址
>>>>>>> fae96c615f08af72ac4b3c03d5870995cbbd51b0

server:
  port: 8085
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      scope: all
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token