auth-server: http://localhost:8080/sso # 认证服务器地址

server:
  port: 8085
security:
  oauth2:
    client:
      client-id: biciclient
      client-secret: bicisecret
      scope: all
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token